apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app1-frontend

  template:
    metadata:
      labels:
        app: app1-frontend

    spec:
      containers:
        - name: frontend
          image: python:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80
